"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

format = """
$directory\
${custom.jj}\
$git_state\
$git_metrics\
$fill\
$terraform\
$pulumi\
$kubernetes\
$aws\
$azure\
$gcloud\
$line_break\
$character
"""

[directory]
style = "bold cyan"
truncate_to_repo = false

[fill]
symbol = " "

[terraform]
format = "via [󱁢 $version]($style) "
style = "bold 105"

[kubernetes]
symbol = "󱄄 "
format = 'at [$symbol$context( \($namespace\))]($style) '
style = "bold blue"

[custom.jj]
description = "Display Jujutsu working copy status"
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "
